# Register api
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
 "identity" : "1111111114",
 # "identity" : "someone@ggg.mail",
 "firstName" : "someone2",
 "lastName" : "c",
 "password" : "123456",
 "confirmPassword" : "123456"
}
###

POST http://localhost:8899/api/auth/login
Content-Type: application/json

{
    "identity" :  "andy@cc21.web",
    "password" :  "a1234"
}
###

GET http://localhost:8899/api/comments
###